### ISSUE TITLE
ReadElem non rileva EOF

### ISSUE THREAD

**Issue by emilianomaccaferri** [prittt/fondamenti-ii#1]
Volevo segnalarle che sembrerebbe che il metodo ReadElem non rilevi EOF.
Non c'è sostanzialmente modo di capire se il file è finito oppure no, dato che la funzione ritorna il valore letto e non controlla che la lettura sia andata a buon fine.

**Comment by prittt** [comment]
Gentile Emiliano Maccaferri, 

grazie per la segnalazione. La funzione in oggetto è stata pensata come estensione dell'acquisizione da standard input e assume che si conosca a priori la presenza o meno dell'elemento su file. Si potrebbero usare le funzioni `feof()`  e `ferror()`, ma concordo comunque con lei sulla sua dubbia utilità.  Nel branch [development](https://github.com/prittt/Fondamenti-II/tree/development) trova un'implementazione alternativa che risolve il problema evidenziato. Faccia attenzione perché lo script di generazione automatica della documentazione è attivo solo sul master, quindi, i link alla documentazione e ai file .zip con i sorgenti puntano ancora al vecchio codice: come spiegato nel readme, trova i nuovi file nella cartella `list>int` del branch.

Ovviamente per l'esercitazione del 15/05/2020 le funzioni non cambieranno. Valuterò e comunicherò a lei e ai suoi colleghi l'eventuale modifica per la prossima esercitazione e per l'esame.
